version:  "3.3" 
services:
       
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  ganache:
    image: trufflesuite/ganache:latest
    restart: always
    ports:
      - "8545:8545"
  
  tool:
    build:
      context: .
      dockerfile: tool.Dockerfile
    stdin_open: true
    depends_on:
      - db
      - ganache
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: password
      DB_NAME: postgres
    links:
      - db