/* author: thiagopandrade@gmail.com */
/* Generated by AceHTML Freeware http://freeware.acehtml.com */
/* Creation date: 23/2/2007 */


function Relatorio() {
	window.open('relatorio.jsp','relatorios','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=580,height=410');
}
