/* author: thiagopandrade@gmail.com */
/* Generated by AceHTML Freeware http://freeware.acehtml.com */
/* Creation date: 23/2/2007 */
function MenuTutor(){
	var buffer = '<div class="tit_menu"><h5>Opções</h5></div>' +
					'<div class="itensmenu">' +
					'	<a href="novo_tutor.jsp">Criar</a>' +
					'	<a href="tutores_disciplina.jsp">Editar/Remover</a>' +
          
					'</div>';
        document.write(buffer);
}

function Relatorio() {
	window.open('relatorio.jsp','relatorios','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=580,height=410');
}
